### PR TITLE
chg: vat rate change for finland starting 2024-09-01

### PR DESCRIPTION
**Pull request by l-naumann**
References: 
https://yle.fi/a/74-20091421
https://www.vero.fi/en/businesses-and-corporations/taxes-and-charges/vat/rates-of-vat/new-vat-rate-from-1-september-2024--instructions-for-vat-reporting/

### CODE REVIEW

**Comment by kdeldycke** [comment]
Good catch! Let's merge!

**Comment by timwhitlock** [comment]
Thanks for this!

Possibly off-topic, but this is the first time I've noticed something... The link above states that services supplied on a continuous basis (in my case, a SaaS subscription) should take the tax rate from the END of the subscription period. This is news to me! Is this common knowledge? Is the rule specific to Finland? It would seem impossible to achieve when the rates change at shorter notice than the billing cycle.

**Comment by GregOriol** [comment]
@timwhitlock Indeed, that's a strange way of applying VAT... I haven't heard of any other rule like this. I don't think it would be possible to change many products to match this.

**Comment by GregOriol** [comment]
Same here: payment on the first day of a monthly service, so tax rate is the one from that date.

**Pull request merged**
